## E2. Introducción a Numpy
`Numpy` es una librería que nos permite manejar arrays multidimensionales de manera eficiente. A continuación, veremos cómo crear y manipular arrays.

In [16]:
# Importar la librería numpy
import numpy as np


### Crear un array
Crea un array a partir de una lista o tupla. (`np.array()`)

In [17]:
# Crear un array de números enteros
a = np.array([1, 2, 3, 4, 5])
print('Array:', a)

Array: [1 2 3 4 5]


### Crear arrays con valores iniciales
Genera arrays con valores predefinidos (`np.zeros()`, `np.ones()`, `np.arange()`)

In [18]:
zeros = np.zeros(5)       # Array de ceros
ones = np.ones((2, 3))    # Matriz 2x3 de unos
rango = np.arange(0, 10, 2)  # Array de 0 a 9 con paso 2
print(zeros)
print(ones)
print(rango)

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]


### Generar un array aleatorio
Genera un array con valores aleatorios entre 0 y 1 (`np.random.random(`)`)

In [19]:
random_arr = np.random.random(5)
print(random_arr)

[0.14102373 0.14204102 0.30303158 0.60919109 0.68849307]


### Acceder a elementos y rangos
Accede a elementos o rangos de un array. (a[index], a[start:end])

In [20]:
print(a[0])      # Primer elemento
print(a[1:4])    # Rango del índice 1 al 3

1
[2 3 4]


### Obtener información del array
Consulta la forma, el tipo de datos y el tamaño del array. (`shape`, `dtype`, `size`)

In [21]:
print(a.shape)   # Dimensiones del array
print(a.dtype)   # Tipo de datos
print(a.size)    # Número total de elementos

(5,)
int64
5


### Operaciones matemáticas
Puedes realizar operaciones matemáticas elementales con los arrays de `numpy` de forma eficiente.

In [22]:
# Sumar 10 a cada elemento del array
b = a + 10
print('Array después de sumar 10:', b)

# Multiplicar cada elemento por 2
c = a * 2
print('Array después de multiplicar por 2:', c)

# Suma elemento a elemento
d =  a + b
print('Array de suma elemento a elemento:', d)

Array después de sumar 10: [11 12 13 14 15]
Array después de multiplicar por 2: [ 2  4  6  8 10]
Array de suma elemento a elemento: [12 14 16 18 20]


### Calcular estadísticas básicas
Calcula estadísticas básicas en el array. (`np.mean()`, `np.max()`, `np.min()`, `np.sum()`)

In [23]:
print("Media:", np.mean(a))
print("Máximo:", np.max(a))
print("Mínimo:", np.min(a))
print("Suma:", np.sum(a))

Media: 3.0
Máximo: 5
Mínimo: 1
Suma: 15


### Filtrar elementos 
Filtra elementos que cumplen con una condición. (`a[condición]`)

In [24]:
filtro = a[a > 3]   # Elementos mayores que 3
print(filtro)

[4 5]


### Arrays multidimensionales
A continuación crearemos un array bidimensional (matriz) con `numpy`.

In [25]:
# Crear una matriz 3x3
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('Matriz 3x3:\n', m)

Matriz 3x3:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
print(m.shape)
print(m[0, 0], m[0, 1], m[1, 0])

(3, 3)
1 2 4


### Operaciones de álgebra lineal
Realiza operaciones de álgebra lineal, como el producto de matrices y la transposición. (`np.dot()`, `np.transpose()`)

In [27]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
producto_matriz = np.dot(A, B)  # Producto matricial
transpuesta = np.transpose(A)   # Transpuesta de A
print(producto_matriz)
print(transpuesta)

[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
